version: '3.9'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeThisWhatYouLike
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/mongodb
      - ./data/mongodb.config/mongod.conf:/etc/mongod.conf
